<div id="header">
	<div class="container">
		<div id="welcomeLine" class="row">
			<div class="span6"> </div>
		</div>
		<!-- Navbar ================================================== -->
		<div id="logoArea" class="navbar">
		<a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>
		  <div class="navbar-inner">
			<a class="brand" href="Inicio.aspx"><img width="240" height="280" src="Ima/deli.png" alt="Bootsshop"/></a>
			<ul id="topMenu" class="nav pull-right">
				<li class=""><a href="Inicio.aspx">Inicio</a></li>
				<li class=""><a href="Catalogo.aspx?tipo=1,2,3">Catálogo</a></li>
				<li class=""><a href="Encuesta.aspx">Recomendación</a></li>
				<li class=""><a href="Contactanos.aspx">Contáctanos</a></li>
				<li class=""></li>
			</ul>
		  </div>
		</div>
	</div>
</div>