<div id="header">
	<div class="container">
		<div id="welcomeLine" class="row">
			<div class="span6">Bienvenido!</div>
			<div class="span6">
				<div class="pull-right">
					<a href="Carrito.aspx"><span class="btn btn-mini btn-primary cart_anchor"><i class="icon-shopping-cart icon-white"></i>Productos del carrito</span> </a> 
				</div>
			</div>
		</div>
		<!-- Navbar ================================================== -->
		<div id="logoArea" class="navbar">
		<a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>
		  <div class="navbar-inner">
			<a class="brand" href="Inicio.aspx"><img width="300" height="350" src="Ima/deli.png" alt="Bootsshop"/></a>
				<input id="srchFld" class="srchTxt" type="text" />
				<select class="srchTxt">
					<option>Todo</option>
					<option>Niños</option>
					<option>Niñas</option>
					<option>Bebes</option>
				</select> 
				<button type="submit" id="submitButton" class="btn btn-primary">Buscar</button>
			<ul id="topMenu" class="nav pull-right">
				<li class=""><a href="Inicio.aspx">Inicio</a></li>
				<li class=""><a href="normal.html">Catalogo</a></li>
				<li class=""><a href="Encuesta.aspx">Encuesta</a></li>
				<li class=""><a href="contact.html">Contactanos</a></li>
				<li class=""></li>
			</ul>
		  </div>
		</div>
	</div>
</div>