<div id="sidebar" class="span3">
	<ul id="sideManu" class="nav nav-tabs nav-stacked">
		<li class="subMenu open"><a> NIÑOS </a>
			<ul>
				<li><a href="Catalogo.aspx?tipo=5,1"><i class="icon-chevron-right"></i>SUPER HEROES</a></li>
				<li><a href="Catalogo.aspx?tipo=12,1"><i class="icon-chevron-right"></i>CARRITOS</a></li>
				<li><a href="Catalogo.aspx?tipo=10"><i class="icon-chevron-right"></i>LANZADORES</a></li>
				<li><a href="Catalogo.aspx?tipo=11,1"><i class="icon-chevron-right"></i>CONSTRUCCION</a></li>
				<li><a href="Catalogo.aspx?tipo=24"><i class="icon-chevron-right"></i>AUTOPISTAS</a></li>
			</ul>
		</li>
		<li class="subMenu"><a> NIÑAS </a>
			<ul style="display:none">
				<li><a href="Catalogo.aspx?tipo=5,2"><i class="icon-chevron-right"></i>SUPER HEROES</a></li>
				<li><a href="Catalogo.aspx?tipo=11,2"><i class="icon-chevron-right"></i>CONSTRUCCION</a></li>												
				<li><a href="Catalogo.aspx?tipo=13"><i class="icon-chevron-right"></i>MASCOTAS</a></li>	
				<li><a href="Catalogo.aspx?tipo=14"><i class="icon-chevron-right"></i>MUÑECAS Y ACCESORIOS</a></li>
				<li><a href="Catalogo.aspx?tipo=15"><i class="icon-chevron-right"></i>MANUALIDADES</a></li>												
				<li><a href="Catalogo.aspx?tipo=12,2"><i class="icon-chevron-right"></i>VEHICULOS</a></li>																							
			</ul>
		</li>
		<li class="subMenu"><a>BEBES</a>
			<ul style="display:none">
				<li><a href="productsBebes_Nacidos.aspx"><i class="icon-chevron-right"></i>RECIEN NACIDOS</a></li>
				<li><a href="ProductsBebe_tapetes.aspx"><i class="icon-chevron-right"></i>TAPETES</a></li>												
				<li><a href="productsBebes_Aprendizaje.aspx"><i class="icon-chevron-right"></i>APRENDIZAJE</a></li>
			</ul>
		</li>
	</ul>
	<br/>
</div>